// =============================================================================
// cartiva - preset-data.js (preset catalogue and color definitions)
// =============================================================================


// -----------------------------------------------------------------------------
// Preset catalogue
// -----------------------------------------------------------------------------
// Display metadata used to populate the preset selector.
window.CartivaPresetCatalog = [
  {
    id: 'alpine',
    name: 'Alpine Snow'
  },
  {
    id: 'amethyst',
    name: 'Amethyst Glow'
  },
  {
    id: 'arctic-archipelago',
    name: 'Arctic Archipelago'
  },
  {
    id: 'arctic-badlands',
    name: 'Arctic Badlands'
  },
  {
    id: 'arctic-delta',
    name: 'Arctic Delta'
  },
  {
    id: 'arctic-estuary',
    name: 'Arctic Estuary'
  },
  {
    id: 'arctic-highlands',
    name: 'Arctic Highlands'
  },
  {
    id: 'autumn',
    name: 'Autumn Rust'
  },
  {
    id: 'azure-delta',
    name: 'Azure Delta'
  },
  {
    id: 'baroque',
    name: 'Baroque Gold'
  },
  {
    id: 'blueprint',
    name: 'Blueprint / Technical'
  },
  {
    id: 'bordeaux',
    name: 'Bordeaux Wine'
  },
  {
    id: 'burnished-archipelago',
    name: 'Burnished Archipelago'
  },
  {
    id: 'burnished-badlands',
    name: 'Burnished Badlands'
  },
  {
    id: 'burnished-delta',
    name: 'Burnished Delta'
  },
  {
    id: 'burnished-estuary',
    name: 'Burnished Estuary'
  },
  {
    id: 'canyon',
    name: 'Canyon Red Rock'
  },
  {
    id: 'celadon',
    name: 'Celadon Breeze'
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard Dark'
  },
  {
    id: 'cherry',
    name: 'Cherry Blossom'
  },
  {
    id: 'citrus',
    name: 'Citrus Punch'
  },
  {
    id: 'cloud-archipelago',
    name: 'Cloud Archipelago'
  },
  {
    id: 'cloud-badlands',
    name: 'Cloud Badlands'
  },
  {
    id: 'cloud-delta',
    name: 'Cloud Delta'
  },
  {
    id: 'cloud-estuary',
    name: 'Cloud Estuary'
  },
  {
    id: 'cloud-highlands',
    name: 'Cloud Highlands'
  },
  {
    id: 'cobalt',
    name: 'Cobalt Spark'
  },
  {
    id: 'coffee',
    name: 'Coffee and Cream'
  },
  {
    id: 'copper',
    name: 'Copper Patina'
  },
  {
    id: 'coral',
    name: 'Coral Reef'
  },
  {
    id: 'crimson',
    name: 'Crimson Night'
  },
  {
    id: 'cyberalt',
    name: 'Cyberpunk Neon Alt'
  },
  {
    id: 'darkmode',
    name: 'Dark Mode / Neon'
  },
  {
    id: 'deep-archipelago',
    name: 'Deep Archipelago'
  },
  {
    id: 'deep-delta',
    name: 'Deep Delta'
  },
  {
    id: 'desert',
    name: 'Desert Sand'
  },
  {
    id: 'electric-highlands',
    name: 'Electric Highlands'
  },
  {
    id: 'elysian',
    name: 'Elysian Fields'
  },
  {
    id: 'emerald',
    name: 'Emerald Forest'
  },
  {
    id: 'fern',
    name: 'Fern Canopy'
  },
  {
    id: 'fiesta',
    name: 'Fiesta Vibrant'
  },
  {
    id: 'forestmist',
    name: 'Forest Mist'
  },
  {
    id: 'frostbite',
    name: 'Frostbite Blue'
  },
  {
    id: 'galaxy',
    name: 'Galaxy Deep'
  },
  {
    id: 'ice',
    name: 'Glacial Ice'
  },
  {
    id: 'glacier',
    name: 'Glacier Blue'
  },
  {
    id: 'golden-estuary',
    name: 'Golden Estuary'
  },
  {
    id: 'granite',
    name: 'Granite Stone'
  },
  {
    id: 'harvest',
    name: 'Harvest Moon'
  },
  {
    id: 'hazelnut',
    name: 'Hazelnut Earth'
  },
  {
    id: 'honey',
    name: 'Honey Amber'
  },
  {
    id: 'horizon',
    name: 'Horizon Line'
  },
  {
    id: 'indigo',
    name: 'Indigo Night'
  },
  {
    id: 'jade-delta',
    name: 'Jade Delta'
  },
  {
    id: 'jungle',
    name: 'Jungle Safari'
  },
  {
    id: 'lagoon',
    name: 'Lagoon Teal'
  },
  {
    id: 'lavender',
    name: 'Lavender Mist'
  },
  {
    id: 'lunar-delta',
    name: 'Lunar Delta'
  },
  {
    id: 'magma',
    name: 'Magma Dark'
  },
  {
    id: 'matrix',
    name: 'Matrix Green'
  },
  {
    id: 'midnight',
    name: 'Midnight Purple'
  },
  {
    id: 'minimalgrey',
    name: 'Minimal Grey'
  },
  {
    id: 'mocha',
    name: 'Mocha Roast'
  },
  {
    id: 'nebula',
    name: 'Nebula Glow'
  },
  {
    id: 'nordic',
    name: 'Nordic Frost'
  },
  {
    id: 'olive',
    name: 'Olive Grove'
  },
  {
    id: 'opal-archipelago',
    name: 'Opal Archipelago'
  },
  {
    id: 'orchid',
    name: 'Orchid Bloom'
  },
  {
    id: 'parchment',
    name: 'Parchment Scroll'
  },
  {
    id: 'pasteldream',
    name: 'Pastel Dream'
  },
  {
    id: 'peacock',
    name: 'Peacock Feather'
  },
  {
    id: 'polar-archipelago',
    name: 'Polar Archipelago'
  },
  {
    id: 'monochrome',
    name: 'Pure Monochrome'
  },
  {
    id: 'quartz',
    name: 'Quartz Crystal'
  },
  {
    id: 'quiet-highlands',
    name: 'Quiet Highlands'
  },
  {
    id: 'radiant-archipelago',
    name: 'Radiant Archipelago'
  },
  {
    id: 'redwood',
    name: 'Redwood Timber'
  },
  {
    id: 'slate',
    name: 'Slate Minimal'
  },
  {
    id: 'solarized',
    name: 'Solarized Light'
  },
  {
    id: 'steampunk',
    name: 'Steampunk Brass'
  },
  {
    id: 'sunset',
    name: 'Sunset Glow'
  },
  {
    id: 'synthwave',
    name: 'Synthwave 80s'
  },
  {
    id: 'tundra',
    name: 'Tundra Frost'
  },
  {
    id: 'velvet-delta',
    name: 'Velvet Delta'
  },
  {
    id: 'warmvintage',
    name: 'Warm Vintage Sepia'
  },
  {
    id: 'wild-archipelago',
    name: 'Wild Archipelago'
  },
  {
    id: 'aero-blue',
    name: 'Aero Blue'
  },
  {
    id: 'alabaster-coast',
    name: 'Alabaster Coast'
  },
  {
    id: 'amber-harbor',
    name: 'Amber Harbor'
  },
  {
    id: 'apricot-bay',
    name: 'Apricot Bay'
  },
  {
    id: 'ash-lagoon',
    name: 'Ash Lagoon'
  },
  {
    id: 'birch-inlet',
    name: 'Birch Inlet'
  },
  {
    id: 'blush-marina',
    name: 'Blush Marina'
  },
  {
    id: 'bronze-cove',
    name: 'Bronze Cove'
  },
  {
    id: 'cedar-sound',
    name: 'Cedar Sound'
  },
  {
    id: 'clay-shore',
    name: 'Clay Shore'
  },
  {
    id: 'cream-fjord',
    name: 'Cream Fjord'
  },
  {
    id: 'denim-bay',
    name: 'Denim Bay'
  },
  {
    id: 'eucalyptus-port',
    name: 'Eucalyptus Port'
  },
  {
    id: 'foggy-marina',
    name: 'Foggy Marina'
  },
  {
    id: 'graphite-coast',
    name: 'Graphite Coast'
  },
  {
    id: 'heather-bay',
    name: 'Heather Bay'
  },
  {
    id: 'linen-lagoon',
    name: 'Linen Lagoon'
  },
  {
    id: 'mango-inlet',
    name: 'Mango Inlet'
  },
  {
    id: 'mauve-harbor',
    name: 'Mauve Harbor'
  },
  {
    id: 'mint-sound',
    name: 'Mint Sound'
  },
  {
    id: 'mossy-cove',
    name: 'Mossy Cove'
  },
  {
    id: 'oatmeal-bay',
    name: 'Oatmeal Bay'
  },
  {
    id: 'ochre-port',
    name: 'Ochre Port'
  },
  {
    id: 'paper-fjord',
    name: 'Paper Fjord'
  },
  {
    id: 'peach-coast',
    name: 'Peach Coast'
  },
  {
    id: 'pine-marina',
    name: 'Pine Marina'
  },
  {
    id: 'plum-inlet',
    name: 'Plum Inlet'
  },
  {
    id: 'porcelain-bay',
    name: 'Porcelain Bay'
  },
  {
    id: 'rosewood-port',
    name: 'Rosewood Port'
  },
  {
    id: 'sage-harbor',
    name: 'Sage Harbor'
  },
  {
    id: 'sandstone-sound',
    name: 'Sandstone Sound'
  },
  {
    id: 'seafoam-coast',
    name: 'Seafoam Coast'
  },
  {
    id: 'shell-lagoon',
    name: 'Shell Lagoon'
  },
  {
    id: 'smoke-bay',
    name: 'Smoke Bay'
  },
  {
    id: 'spruce-inlet',
    name: 'Spruce Inlet'
  },
  {
    id: 'stone-marina',
    name: 'Stone Marina'
  },
  {
    id: 'terracotta-cove',
    name: 'Terracotta Cove'
  },
  {
    id: 'thistle-shore',
    name: 'Thistle Shore'
  },
  {
    id: 'umber-bay',
    name: 'Umber Bay'
  },
  {
    id: 'vanilla-port',
    name: 'Vanilla Port'
  },
  {
    id: 'willow-fjord',
    name: 'Willow Fjord'
  },
  {
    id: 'winter-harbor',
    name: 'Winter Harbor'
  },
  {
    id: 'wisteria-coast',
    name: 'Wisteria Coast'
  },
  {
    id: 'woodland-bay',
    name: 'Woodland Bay'
  },
  {
    id: 'zinc-marina',
    name: 'Zinc Marina'
  },
  {
    id: 'cocoa-inlet',
    name: 'Cocoa Inlet'
  },
  {
    id: 'coral-harbor',
    name: 'Coral Harbor'
  },
  {
    id: 'fern-coast',
    name: 'Fern Coast'
  },
  {
    id: 'lilac-bay',
    name: 'Lilac Bay'
  },
  { id: 'pebble-port', name: 'Pebble Port' },
  {
    id: 'kandinsky',
    name: 'Kandinsky'
  },
  {
    id: 'schwarzlicht',
    name: 'Schwarzlicht'
  },
  {
    id: 'testei',
    name: 'testei'
  }
];


// -----------------------------------------------------------------------------
// Preset color definitions
// -----------------------------------------------------------------------------
// Each preset maps UI control IDs to colors, opacity values, and visibility flags.
// Preset definitions are kept in one shared object so the UI and rendering
// logic can use the same values without duplicating color settings.
window.CartivaPresetData = {

      'darkmode': {
        waterColor: '#1e3a8a', waterOpacity: '100', waterToggle: true,
        forestColor: '#064e3b', forestColorAccent: '#065f46', forestOpacity: '100', forestToggle: true,
        landColor: '#111827', landOpacity: '100', landToggle: true,
        landCoverColor: '#1f2937', landCoverColorAccent: '#374151', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#9ca3af', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#4b5563', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#374151', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#6b7280'
      },
      'kandinsky': {
        waterColor: '#4cc9f0', waterwayColor: '#0077b6', waterShadowColor: '#4361ee', waterOpacity: '100', waterToggle: true,
        forestColor: '#2a9d8f', forestColorAccent: '#f4d35e', parkColor: '#f4d35e', natureReserveColor: '#43aa8b', grassColor: '#90be6d', woodColor: '#277da1', forestOpacity: '100', forestToggle: true,
        landColor: '#f7e7c6', landOpacity: '100', landToggle: true,
        landCoverColor: '#f2a65a', landCoverColorAccent: '#e76f51', residentialColor: '#e76f51', cemeteryColor: '#8ac926', stadiumColor: '#ffca3a', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#263238', roadCaseColor: '#f7e7c6', motorwayColor: '#e63946', trunkRoadColor: '#f77f00', primaryRoadColor: '#ffca3a', secondaryRoadColor: '#1982c4', minorRoadColor: '#6a4c93', serviceRoadColor: '#495057', pathColor: '#2a9d8f', railColor: '#8338ec', bridgeColor: '#ffffff', bridgeCaseColor: '#1d3557', tunnelColor: '#6c757d', tunnelCaseColor: '#212529', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#6a4c93', countryBoundaryColor: '#1d3557', stateBoundaryColor: '#8338ec', countyBoundaryColor: '#1982c4', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#ffadad', buildingTopColor: '#ff6b6b', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#1d3557'
      },
      'schwarzlicht': {
        waterColor: '#00d5ff', waterwayColor: '#6dfcff', waterShadowColor: '#191970', waterOpacity: '100', waterToggle: true,
        forestColor: '#00c46a', forestColorAccent: '#00ff9c', parkColor: '#00ff9c', natureReserveColor: '#16f7d2', grassColor: '#35ff7d', woodColor: '#008f5a', forestOpacity: '100', forestToggle: true,
        landColor: '#090012', landOpacity: '100', landToggle: true,
        landCoverColor: '#140022', landCoverColorAccent: '#2b1648', residentialColor: '#2b1648', cemeteryColor: '#8cff66', stadiumColor: '#ffea00', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#ffffff', roadCaseColor: '#24003d', motorwayColor: '#ff2fd6', motorwayCaseColor: '#ff00aa', trunkRoadColor: '#ff7a00', primaryRoadColor: '#fff000', secondaryRoadColor: '#00f0ff', minorRoadColor: '#ffffff', serviceRoadColor: '#9bfffc', pathColor: '#73ff66', railColor: '#ff66ff', bridgeColor: '#ffffff', bridgeCaseColor: '#ffcc00', tunnelColor: '#6b5cff', tunnelCaseColor: '#270045', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#5ffcff', countryBoundaryColor: '#ffffff', stateBoundaryColor: '#ff4fd8', countyBoundaryColor: '#5ffcff', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#19002f', buildingTopColor: '#ff4fd8', buildingOpacity: '95', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#ffffff'
      },
	  'testei': {
        waterColor: '#6e9adb', waterwayColor: '#4f6e9c', waterShadowColor: '#6e9adb', waterOpacity: '100', waterToggle: true,
        forestColor: '#509648', forestColorAccent: '#3f7538', parkColor: '#509648', natureReserveColor: '#509648', grassColor: '#67b05f', woodColor: '#4cb83e', forestOpacity: '100', forestToggle: true,
        landColor: '#f1f0f2', landOpacity: '100', landToggle: true,
        landCoverColor: '#bebdbf', landCoverColorAccent: '#bebdbf', residentialColor: '#bebdbf', cemeteryColor: '#bebdbf', stadiumColor: '#bebdbf', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#3d3d3d', roadCaseColor: '#3d3d3d', motorwayColor: '#3d3d3d', motorwayCaseColor: '#3d3d3d', trunkRoadColor: '#3d3d3d', primaryRoadColor: '#3d3d3d', secondaryRoadColor: '#3d3d3d', minorRoadColor: '#3d3d3d', serviceRoadColor: '#3d3d3d', pathColor: '#3d3d3d', railColor: '#3d3d3d', bridgeColor: '#3d3d3d', bridgeCaseColor: '#3d3d3d', tunnelColor: '#3d3d3d', tunnelCaseColor: '#3d3d3d', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#5ffcff', countryBoundaryColor: '#595757', stateBoundaryColor: '#8f2222', countyBoundaryColor: '#5ffcff', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#969595', buildingTopColor: '#969595', buildingOpacity: '95', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#3d3d3d'
      },
      'blueprint': {
        waterColor: '#1d4ed8', waterOpacity: '100', waterToggle: true,
        forestColor: '#1e40af', forestColorAccent: '#2563eb', forestOpacity: '100', forestToggle: true,
        landColor: '#0f172a', landOpacity: '100', landToggle: true,
        landCoverColor: '#1e293b', landCoverColorAccent: '#334155', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#60a5fa', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#93c5fd', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#1e3a8a', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#93c5fd'
      },
      'warmvintage': {
        waterColor: '#93c5fd', waterOpacity: '100', waterToggle: true,
        forestColor: '#d1fae5', forestColorAccent: '#a7f3d0', forestOpacity: '100', forestToggle: true,
        landColor: '#fdf6e2', landOpacity: '100', landToggle: true,
        landCoverColor: '#faedcd', landCoverColorAccent: '#fefae0', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#bc6c25', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#dda15e', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#e9d8a6', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#dda15e'
      },
      'emerald': {
        waterColor: '#38bdf8', waterOpacity: '100', waterToggle: true,
        forestColor: '#047857', forestColorAccent: '#059669', forestOpacity: '100', forestToggle: true,
        landColor: '#ecfdf5', landOpacity: '100', landToggle: true,
        landCoverColor: '#d1fae5', landCoverColorAccent: '#a7f3d0', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#064e3b', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#6ee7b7', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#a7f3d0', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#059669'
      },
      'sunset': {
        waterColor: '#f43f5e', waterOpacity: '100', waterToggle: true,
        forestColor: '#7c2d12', forestColorAccent: '#9a3412', forestOpacity: '100', forestToggle: true,
        landColor: '#fff1f2', landOpacity: '100', landToggle: true,
        landCoverColor: '#ffe4e6', landCoverColorAccent: '#fecdd3', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#881337', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#fb7185', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fecdd3', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#f43f5e'
      },
      'midnight': {
        waterColor: '#6366f1', waterOpacity: '100', waterToggle: true,
        forestColor: '#312e81', forestColorAccent: '#3730a3', forestOpacity: '100', forestToggle: true,
        landColor: '#030712', landOpacity: '100', landToggle: true,
        landCoverColor: '#111827', landCoverColorAccent: '#1f2937', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#a5b4fc', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#4f46e5', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#1e1b4b', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#818cf8'
      },
      'autumn': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#b45309', forestColorAccent: '#d97706', forestOpacity: '100', forestToggle: true,
        landColor: '#fffbeb', landOpacity: '100', landToggle: true,
        landCoverColor: '#fef3c7', landCoverColorAccent: '#fde68a', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#78350f', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#f59e0b', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fde68a', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#d97706'
      },
      'minimalgrey': {
        waterColor: '#94a3b8', waterOpacity: '100', waterToggle: true,
        forestColor: '#cbd5e1', forestColorAccent: '#e2e8f0', forestOpacity: '100', forestToggle: true,
        landColor: '#f8fafc', landOpacity: '100', landToggle: true,
        landCoverColor: '#f1f5f9', landCoverColorAccent: '#e2e8f0', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#475569', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#cbd5e1', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#e2e8f0', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#cbd5e1'
      },
      'cyberalt': {
        waterColor: '#22d3ee', waterOpacity: '100', waterToggle: true,
        forestColor: '#a21caf', forestColorAccent: '#c084fc', forestOpacity: '100', forestToggle: true,
        landColor: '#09090b', landOpacity: '100', landToggle: true,
        landCoverColor: '#18181b', landCoverColorAccent: '#27272a', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#f43f5e', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#a855f7', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#27272a', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#22d3ee'
      },
      'pasteldream': {
        waterColor: '#bae6fd', waterOpacity: '100', waterToggle: true,
        forestColor: '#fed7aa', forestColorAccent: '#ffedd5', forestOpacity: '100', forestToggle: true,
        landColor: '#fdf4ff', landOpacity: '100', landToggle: true,
        landCoverColor: '#fae8ff', landCoverColorAccent: '#f5d0fe', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#c084fc', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#e879f9', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#f5d0fe', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#e879f9'
      },
      'nordic': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#334155', forestColorAccent: '#475569', forestOpacity: '100', forestToggle: true,
        landColor: '#f1f5f9', landOpacity: '100', landToggle: true,
        landCoverColor: '#e2e8f0', landCoverColorAccent: '#cbd5e1', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#0f172a', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#64748b', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#cbd5e1', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#94a3b8'
      },
      'desert': {
        waterColor: '#38bdf8', waterOpacity: '100', waterToggle: true,
        forestColor: '#ca8a04', forestColorAccent: '#eab308', forestOpacity: '100', forestToggle: true,
        landColor: '#fefce8', landOpacity: '100', landToggle: true,
        landCoverColor: '#fef9c3', landCoverColorAccent: '#fef08a', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#854d0e', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#ca8a04', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fef08a', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#eab308'
      },
      'cherry': {
        waterColor: '#7dd3fc', waterOpacity: '100', waterToggle: true,
        forestColor: '#fda4af', forestColorAccent: '#fecdd3', forestOpacity: '100', forestToggle: true,
        landColor: '#fff1f2', landOpacity: '100', landToggle: true,
        landCoverColor: '#ffe4e6', landCoverColorAccent: '#fecdd3', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#9f1239', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#fb7185', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fecdd3', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#f43f5e'
      },
      'coffee': {
        waterColor: '#7dd3fc', waterOpacity: '100', waterToggle: true,
        forestColor: '#78350f', forestColorAccent: '#92400e', forestOpacity: '100', forestToggle: true,
        landColor: '#fef3c7', landOpacity: '100', landToggle: true,
        landCoverColor: '#fde68a', landCoverColorAccent: '#fcd34d', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#451a03', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#b45309', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fcd34d', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#92400e'
      },
      'lavender': {
        waterColor: '#a78bfa', waterOpacity: '100', waterToggle: true,
        forestColor: '#c4b5fd', forestColorAccent: '#ddd6fe', forestOpacity: '100', forestToggle: true,
        landColor: '#f5f3ff', landOpacity: '100', landToggle: true,
        landCoverColor: '#ede9fe', landCoverColorAccent: '#ddd6fe', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#5b21b6', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#8b5cf6', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#ddd6fe', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#7c3aed'
      },
      'synthwave': {
        waterColor: '#ff007f', waterOpacity: '100', waterToggle: true,
        forestColor: '#7928ca', forestColorAccent: '#8a2be2', forestOpacity: '100', forestToggle: true,
        landColor: '#120428', landOpacity: '100', landToggle: true,
        landCoverColor: '#1a0b36', landCoverColorAccent: '#2b1055', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#00f0ff', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#ff007f', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#2b1055', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#00f0ff'
      },
      'olive': {
        waterColor: '#60a5fa', waterOpacity: '100', waterToggle: true,
        forestColor: '#365314', forestColorAccent: '#3f6212', forestOpacity: '100', forestToggle: true,
        landColor: '#fefce8', landOpacity: '100', landToggle: true,
        landCoverColor: '#fef08a', landCoverColorAccent: '#fde047', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#1a2e05', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#65a30d', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fde047', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#4d7c0f'
      },
      'crimson': {
        waterColor: '#38bdf8', waterOpacity: '100', waterToggle: true,
        forestColor: '#881337', forestColorAccent: '#9f1239', forestOpacity: '100', forestToggle: true,
        landColor: '#fff1f2', landOpacity: '100', landToggle: true,
        landCoverColor: '#ffe4e6', landCoverColorAccent: '#fecdd3', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#4c0519', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#e11d48', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fecdd3', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#be123c'
      },
      'solarized': {
        waterColor: '#268bd2', waterOpacity: '100', waterToggle: true,
        forestColor: '#859900', forestColorAccent: '#b58900', forestOpacity: '100', forestToggle: true,
        landColor: '#fdf6e3', landOpacity: '100', landToggle: true,
        landCoverColor: '#eee8d5', landCoverColorAccent: '#93a1a1', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#cb4b16', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#657b83', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#eee8d5', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#839496'
      },
      'matrix': {
        waterColor: '#004d40', waterOpacity: '100', waterToggle: true,
        forestColor: '#003300', forestColorAccent: '#004400', forestOpacity: '100', forestToggle: true,
        landColor: '#000d08', landOpacity: '100', landToggle: true,
        landCoverColor: '#001a12', landCoverColorAccent: '#002b1d', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#00ff66', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#008f53', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#002b1d', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#00ff66'
      },
      'coral': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#f43f5e', forestColorAccent: '#fb7185', forestOpacity: '100', forestToggle: true,
        landColor: '#fffaf0', landOpacity: '100', landToggle: true,
        landCoverColor: '#ffedd5', landCoverColorAccent: '#fed7aa', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#9a3412', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#fb923c', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fed7aa', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#f97316'
      },
      'slate': {
        waterColor: '#38bdf8', waterOpacity: '100', waterToggle: true,
        forestColor: '#475569', forestColorAccent: '#64748b', forestOpacity: '100', forestToggle: true,
        landColor: '#0f172a', landOpacity: '100', landToggle: true,
        landCoverColor: '#1e293b', landCoverColorAccent: '#334155', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#e2e8f0', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#475569', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#334155', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#94a3b8'
      },
      'honey': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#b45309', forestColorAccent: '#d97706', forestOpacity: '100', forestToggle: true,
        landColor: '#fffbeb', landOpacity: '100', landToggle: true,
        landCoverColor: '#fef3c7', landCoverColorAccent: '#fde68a', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#78350f', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#f59e0b', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fde68a', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#d97706'
      },
      'ice': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#7dd3fc', forestColorAccent: '#bae6fd', forestOpacity: '100', forestToggle: true,
        landColor: '#f0fdf4', landOpacity: '100', landToggle: true,
        landCoverColor: '#e0f2fe', landCoverColorAccent: '#bae6fd', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#0369a1', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#38bdf8', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#bae6fd', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#0284c7'
      },
      'magma': {
        waterColor: '#3b82f6', waterOpacity: '100', waterToggle: true,
        forestColor: '#9a3412', forestColorAccent: '#c2410c', forestOpacity: '100', forestToggle: true,
        landColor: '#1c1917', landOpacity: '100', landToggle: true,
        landCoverColor: '#292524', landCoverColorAccent: '#44403c', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#f97316', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#ea580c', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#44403c', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#fb923c'
      },
      'forestmist': {
        waterColor: '#7dd3fc', waterOpacity: '100', waterToggle: true,
        forestColor: '#065f46', forestColorAccent: '#047857', forestOpacity: '100', forestToggle: true,
        landColor: '#f0fdf4', landOpacity: '100', landToggle: true,
        landCoverColor: '#dcfce7', landCoverColorAccent: '#bbf7d0', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#166534', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#4ade80', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#bbf7d0', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#22c55e'
      },
      'steampunk': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#78350f', forestColorAccent: '#92400e', forestOpacity: '100', forestToggle: true,
        landColor: '#292524', landOpacity: '100', landToggle: true,
        landCoverColor: '#44403c', landCoverColorAccent: '#57534e', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#d97706', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#b45309', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#57534e', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#f59e0b'
      },
      'amethyst': {
        waterColor: '#38bdf8', waterOpacity: '100', waterToggle: true,
        forestColor: '#581c87', forestColorAccent: '#6b21a8', forestOpacity: '100', forestToggle: true,
        landColor: '#2e1065', landOpacity: '100', landToggle: true,
        landCoverColor: '#3b0764', landCoverColorAccent: '#581c87', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#c084fc', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#9333ea', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#581c87', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#d8b4fe'
      },
      'monochrome': {
        waterColor: '#000000', waterOpacity: '100', waterToggle: true,
        forestColor: '#333333', forestColorAccent: '#666666', forestOpacity: '100', forestToggle: true,
        landColor: '#ffffff', landOpacity: '100', landToggle: true,
        landCoverColor: '#f2f2f2', landCoverColorAccent: '#e6e6e6', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#000000', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#000000', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#cccccc', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#000000'
      },
      'alpine': {
        waterColor: '#7dd3fc',
        forestColor: '#475569',
        forestColorAccent: '#475569',
        landColor: '#f8fafc',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#1e293b',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'baroque': {
        waterColor: '#b45309',
        forestColor: '#78350f',
        forestColorAccent: '#78350f',
        landColor: '#fef3c7',
        landCoverColor: '#fde68a',
        landCoverColorAccent: '#fde68a',
        roadColor: '#451a03',
        boundaryColor: '#d97706',
        buildingColor: '#fcd34d',
        buildingOutlineColor: '#92400e',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'bordeaux': {
        waterColor: '#38bdf8',
        forestColor: '#881337',
        forestColorAccent: '#881337',
        landColor: '#fff1f2',
        landCoverColor: '#ffe4e6',
        landCoverColorAccent: '#ffe4e6',
        roadColor: '#4c0519',
        boundaryColor: '#be123c',
        buildingColor: '#fecdd3',
        buildingOutlineColor: '#9f1239',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'canyon': {
        waterColor: '#0284c7',
        forestColor: '#9a3412',
        forestColorAccent: '#9a3412',
        landColor: '#fff7ed',
        landCoverColor: '#ffedd5',
        landCoverColorAccent: '#ffedd5',
        roadColor: '#7c2d12',
        boundaryColor: '#ea580c',
        buildingColor: '#fed7aa',
        buildingOutlineColor: '#c2410c',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'celadon': {
        waterColor: '#38bdf8',
        forestColor: '#065f46',
        forestColorAccent: '#065f46',
        landColor: '#f0fdf4',
        landCoverColor: '#dcfce7',
        landCoverColorAccent: '#dcfce7',
        roadColor: '#14532d',
        boundaryColor: '#10b981',
        buildingColor: '#bbf7d0',
        buildingOutlineColor: '#059669',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'chalkboard': {
        waterColor: '#38bdf8',
        forestColor: '#334155',
        forestColorAccent: '#334155',
        landColor: '#1e293b',
        landCoverColor: '#334155',
        landCoverColorAccent: '#334155',
        roadColor: '#f8fafc',
        boundaryColor: '#64748b',
        buildingColor: '#475569',
        buildingOutlineColor: '#94a3b8',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'citrus': {
        waterColor: '#0284c7',
        forestColor: '#ca8a04',
        forestColorAccent: '#ca8a04',
        landColor: '#fefce8',
        landCoverColor: '#fef9c3',
        landCoverColorAccent: '#fef9c3',
        roadColor: '#713f12',
        boundaryColor: '#eab308',
        buildingColor: '#fef08a',
        buildingOutlineColor: '#ca8a04',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'cobalt': {
        waterColor: '#60a5fa',
        forestColor: '#1e3a8a',
        forestColorAccent: '#1e3a8a',
        landColor: '#eff6ff',
        landCoverColor: '#dbeafe',
        landCoverColorAccent: '#dbeafe',
        roadColor: '#172554',
        boundaryColor: '#3b82f6',
        buildingColor: '#bfdbfe',
        buildingOutlineColor: '#2563eb',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'copper': {
        waterColor: '#0284c7',
        forestColor: '#78350f',
        forestColorAccent: '#78350f',
        landColor: '#292524',
        landCoverColor: '#44403c',
        landCoverColorAccent: '#44403c',
        roadColor: '#fb923c',
        boundaryColor: '#d97706',
        buildingColor: '#57534e',
        buildingOutlineColor: '#f59e0b',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'cosmic': {
        waterColor: '#ec4899',
        forestColor: '#6b21a8',
        forestColorAccent: '#6b21a8',
        landColor: '#090514',
        landCoverColor: '#1e1b4b',
        landCoverColorAccent: '#1e1b4b',
        roadColor: '#38bdf8',
        boundaryColor: '#a855f7',
        buildingColor: '#312e81',
        buildingOutlineColor: '#c084fc',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'dusk': {
        waterColor: '#f43f5e',
        forestColor: '#4c1d95',
        forestColorAccent: '#4c1d95',
        landColor: '#1e1b4b',
        landCoverColor: '#312e81',
        landCoverColorAccent: '#312e81',
        roadColor: '#fcd34d',
        boundaryColor: '#8b5cf6',
        buildingColor: '#3730a3',
        buildingOutlineColor: '#a78bfa',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'elysian': {
        waterColor: '#38bdf8',
        forestColor: '#15803d',
        forestColorAccent: '#15803d',
        landColor: '#f0fdf4',
        landCoverColor: '#dcfce7',
        landCoverColorAccent: '#dcfce7',
        roadColor: '#166534',
        boundaryColor: '#22c55e',
        buildingColor: '#bbf7d0',
        buildingOutlineColor: '#16a34a',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'fern': {
        waterColor: '#0284c7',
        forestColor: '#14532d',
        forestColorAccent: '#14532d',
        landColor: '#f4fbf7',
        landCoverColor: '#e6f4ed',
        landCoverColorAccent: '#e6f4ed',
        roadColor: '#064e3b',
        boundaryColor: '#059669',
        buildingColor: '#cce8d8',
        buildingOutlineColor: '#047857',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'fiesta': {
        waterColor: '#06b6d4',
        forestColor: '#f43f5e',
        forestColorAccent: '#f43f5e',
        landColor: '#fffbeb',
        landCoverColor: '#fef3c7',
        landCoverColorAccent: '#fef3c7',
        roadColor: '#b91c1c',
        boundaryColor: '#f59e0b',
        buildingColor: '#fde68a',
        buildingOutlineColor: '#d97706',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'frostbite': {
        waterColor: '#38bdf8',
        forestColor: '#0284c7',
        forestColorAccent: '#0284c7',
        landColor: '#f0f9ff',
        landCoverColor: '#e0f2fe',
        landCoverColorAccent: '#e0f2fe',
        roadColor: '#0c4a6e',
        boundaryColor: '#0ea5e9',
        buildingColor: '#bae6fd',
        buildingOutlineColor: '#0284c7',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'galaxy': {
        waterColor: '#3b82f6',
        forestColor: '#581c87',
        forestColorAccent: '#581c87',
        landColor: '#030712',
        landCoverColor: '#0f172a',
        landCoverColorAccent: '#0f172a',
        roadColor: '#f43f5e',
        boundaryColor: '#8b5cf6',
        buildingColor: '#1e1b4b',
        buildingOutlineColor: '#a855f7',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'glacier': {
        waterColor: '#0284c7',
        forestColor: '#64748b',
        forestColorAccent: '#64748b',
        landColor: '#f8fafc',
        landCoverColor: '#f1f5f9',
        landCoverColorAccent: '#f1f5f9',
        roadColor: '#0f172a',
        boundaryColor: '#94a3b8',
        buildingColor: '#e2e8f0',
        buildingOutlineColor: '#cbd5e1',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'granite': {
        waterColor: '#475569',
        forestColor: '#334155',
        forestColorAccent: '#334155',
        landColor: '#f1f5f9',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#0f172a',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'harvest': {
        waterColor: '#0284c7',
        forestColor: '#b45309',
        forestColorAccent: '#b45309',
        landColor: '#fffbeb',
        landCoverColor: '#fef3c7',
        landCoverColorAccent: '#fef3c7',
        roadColor: '#78350f',
        boundaryColor: '#d97706',
        buildingColor: '#fde68a',
        buildingOutlineColor: '#b45309',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'hazelnut': {
        waterColor: '#38bdf8',
        forestColor: '#78350f',
        forestColorAccent: '#78350f',
        landColor: '#fdf8f6',
        landCoverColor: '#f5ebe0',
        landCoverColorAccent: '#f5ebe0',
        roadColor: '#432818',
        boundaryColor: '#b08968',
        buildingColor: '#d5bdaf',
        buildingOutlineColor: '#9c6644',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'horizon': {
        waterColor: '#0284c7',
        forestColor: '#0f172a',
        forestColorAccent: '#0f172a',
        landColor: '#f8fafc',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#334155',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'indigo': {
        waterColor: '#38bdf8',
        forestColor: '#3730a3',
        forestColorAccent: '#3730a3',
        landColor: '#eef2ff',
        landCoverColor: '#e0e7ff',
        landCoverColorAccent: '#e0e7ff',
        roadColor: '#312e81',
        boundaryColor: '#6366f1',
        buildingColor: '#c7d2fe',
        buildingOutlineColor: '#4f46e5',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'jungle': {
        waterColor: '#38bdf8',
        forestColor: '#14532d',
        forestColorAccent: '#14532d',
        landColor: '#f0fdf4',
        landCoverColor: '#dcfce7',
        landCoverColorAccent: '#dcfce7',
        roadColor: '#052e16',
        boundaryColor: '#15803d',
        buildingColor: '#bbf7d0',
        buildingOutlineColor: '#16a34a',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'lagoon': {
        waterColor: '#0284c7',
        forestColor: '#0f766e',
        forestColorAccent: '#0f766e',
        landColor: '#f0fdfa',
        landCoverColor: '#ccfbf1',
        landCoverColorAccent: '#ccfbf1',
        roadColor: '#134e4a',
        boundaryColor: '#14b8a6',
        buildingColor: '#99f6e4',
        buildingOutlineColor: '#0d9488',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'mocha': {
        waterColor: '#7dd3fc',
        forestColor: '#5c4033',
        forestColorAccent: '#5c4033',
        landColor: '#f5deb3',
        landCoverColor: '#deb887',
        landCoverColorAccent: '#deb887',
        roadColor: '#3e2723',
        boundaryColor: '#8b4513',
        buildingColor: '#d2b48c',
        buildingOutlineColor: '#a0522d',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'nebula': {
        waterColor: '#ec4899',
        forestColor: '#9333ea',
        forestColorAccent: '#9333ea',
        landColor: '#0f051d',
        landCoverColor: '#1e0c38',
        landCoverColorAccent: '#1e0c38',
        roadColor: '#22d3ee',
        boundaryColor: '#c084fc',
        buildingColor: '#2e1065',
        buildingOutlineColor: '#d8b4fe',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'orchid': {
        waterColor: '#38bdf8',
        forestColor: '#a21caf',
        forestColorAccent: '#a21caf',
        landColor: '#fdf4ff',
        landCoverColor: '#fae8ff',
        landCoverColorAccent: '#fae8ff',
        roadColor: '#701a75',
        boundaryColor: '#d946ef',
        buildingColor: '#f5d0fe',
        buildingOutlineColor: '#c084fc',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'parchment': {
        waterColor: '#60a5fa',
        forestColor: '#a16207',
        forestColorAccent: '#a16207',
        landColor: '#fefae0',
        landCoverColor: '#faedcd',
        landCoverColorAccent: '#faedcd',
        roadColor: '#654321',
        boundaryColor: '#dda15e',
        buildingColor: '#e9d8a6',
        buildingOutlineColor: '#bc6c25',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'peacock': {
        waterColor: '#38bdf8',
        forestColor: '#047857',
        forestColorAccent: '#047857',
        landColor: '#ecfdf5',
        landCoverColor: '#d1fae5',
        landCoverColorAccent: '#d1fae5',
        roadColor: '#064e3b',
        boundaryColor: '#10b981',
        buildingColor: '#a7f3d0',
        buildingOutlineColor: '#059669',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'quartz': {
        waterColor: '#7dd3fc',
        forestColor: '#cbd5e1',
        forestColorAccent: '#cbd5e1',
        landColor: '#f8fafc',
        landCoverColor: '#f1f5f9',
        landCoverColorAccent: '#f1f5f9',
        roadColor: '#334155',
        boundaryColor: '#94a3b8',
        buildingColor: '#e2e8f0',
        buildingOutlineColor: '#cbd5e1',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'redwood': {
        waterColor: '#38bdf8',
        forestColor: '#7f1d1d',
        forestColorAccent: '#7f1d1d',
        landColor: '#fef2f2',
        landCoverColor: '#fee2e2',
        landCoverColorAccent: '#fee2e2',
        roadColor: '#450a0a',
        boundaryColor: '#dc2626',
        buildingColor: '#fecaca',
        buildingOutlineColor: '#b91c1c',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'tundra': {
        waterColor: '#38bdf8',
        forestColor: '#475569',
        forestColorAccent: '#475569',
        landColor: '#f1f5f9',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#1e293b',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'arctic-archipelago': {
        waterColor: '#2864b4',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#14502d',
        forestColorAccent: '#37824b',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#e1ebd7',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#cdd7c3',
        landCoverColorAccent: '#b9c8af',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#2d2337',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#785064',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#afa59b',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#55464b'
      },
      'arctic-badlands': {
        waterColor: '#396bbf',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#216330',
        forestColorAccent: '#409350',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#e4f0de',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#d2dece',
        landCoverColorAccent: '#c0d1bc',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#382a3c',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#855b6b',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#b4aea6',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#5c5354'
      },
      'arctic-delta': {
        waterColor: '#4a72ca',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#2e7633',
        forestColorAccent: '#49a455',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#e7f5e5',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#d7e5d9',
        landCoverColorAccent: '#c7dac9',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#433141',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#926672',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#b9b7b1',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#63605d'
      },
      'arctic-estuary': {
        waterColor: '#5b79d5',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#3b8936',
        forestColorAccent: '#52b55a',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#eafaec',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#dcece4',
        landCoverColorAccent: '#cee3d6',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#4e3846',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#9f7179',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#bec0bc',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#6a6d66'
      },
      'arctic-highlands': {
        waterColor: '#6c80e0',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#489c39',
        forestColorAccent: '#5bc65f',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#edfff3',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#e1f3ef',
        landCoverColorAccent: '#d5ece3',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#593f4b',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#ac7c80',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#c3c9c7',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#717a6f'
      },
      'azure-delta': {
        waterColor: '#2563eb',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#6fd542',
        forestColorAccent: '#76f96e',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#f60e08',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#f00810',
        landCoverColorAccent: '#ea070a',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#7a545a',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#d39d95',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#d2e4e8',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#86a18a'
      },
      'burnished-archipelago': {
        waterColor: '#0891b2',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#960e4b',
        forestColorAccent: '#912c7d',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#ff1d1d',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#ff1d31',
        landCoverColorAccent: '#ff2231',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#9b6969',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#fabeaa',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#e1ff09',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#9bc8a5'
      },
      'burnished-badlands': {
        waterColor: '#0369a1',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#a3214e',
        forestColorAccent: '#9a3d82',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#022224',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#04243c',
        landCoverColorAccent: '#062b3e',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#a6706e',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#07c9b1',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#e60814',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#a2d5ae'
      },
      'burnished-delta': {
        waterColor: '#38bdf8',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#b03451',
        forestColorAccent: '#a34e87',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#05272b',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#092b47',
        landCoverColorAccent: '#0d344b',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#b17773',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#14d4b8',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#eb111f',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#a9e2b7'
      },
      'burnished-estuary': {
        waterColor: '#0284c7',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#bd4754',
        forestColorAccent: '#ac5f8c',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#082c32',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#0e3252',
        landCoverColorAccent: '#143d58',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#bc7e78',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#21dfbf',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#f01a2a',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#b0efc0'
      },
      'cloud-archipelago': {
        waterColor: '#bae6fd',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#d76d5a',
        forestColorAccent: '#be8196',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#0e3640',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#184068',
        landCoverColorAccent: '#224f72',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#d28c82',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#3bf5cd',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#fa2c40',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#be09d2'
      },
      'cloud-badlands': {
        waterColor: '#7dd3fc',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#e4805d',
        forestColorAccent: '#c7929b',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#113b47',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#1d4773',
        landCoverColorAccent: '#29587f',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#dd9387',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#4800d4',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#ff354b',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#c516db'
      },
      'cloud-delta': {
        waterColor: '#93c5fd',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#f19360',
        forestColorAccent: '#d0a3a0',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#14404e',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#224e7e',
        landCoverColorAccent: '#30618c',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#e89a8c',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#550bdb',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#043e56',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#cc23e4'
      },
      'cloud-estuary': {
        waterColor: '#60a5fa',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#fea663',
        forestColorAccent: '#d9b4a5',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#174555',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#275589',
        landCoverColorAccent: '#376a99',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#f3a191',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#6216e2',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#094761',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#d330ed'
      },
      'cloud-highlands': {
        waterColor: '#38bdf8',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#0bb966',
        forestColorAccent: '#e2c5aa',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#1a4a5c',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#2c5c94',
        landCoverColorAccent: '#3e73a6',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#fea896',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#6f21e9',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#0e506c',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#da3df6'
      },
      'deep-archipelago': {
        waterColor: '#1e3a8a',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#18cc69',
        forestColorAccent: '#ebd6af',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#1d4f63',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#31639f',
        landCoverColorAccent: '#457cb3',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#09af9b',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#7c2cf0',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#135977',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#e14aff'
      },
      'deep-delta': {
        waterColor: '#172554',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#32f26f',
        forestColorAccent: '#fdf8b9',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#235971',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#3b71b5',
        landCoverColorAccent: '#538ecd',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#1fbda5',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#9642fe',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#1d6b8d',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#ef6411'
      },
      'electric-highlands': {
        waterColor: '#152ff3',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#8d7784',
        forestColorAccent: '#3c6fdc',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#387ca2',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#5ea202',
        landCoverColorAccent: '#84cd28',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#6ceec8',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#f18f2f',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#40aada',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#20bf50'
      },
      'golden-estuary': {
        waterColor: '#594b1f',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#c1c390',
        forestColorAccent: '#60b3f0',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#4490be',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#72be2e',
        landCoverColorAccent: '#a0f15c',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#980adc',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#25bb4b',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#54ce06',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#3cf374'
      },
      'jade-delta': {
        waterColor: '#47adb9',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#77cdba',
        forestColorAccent: '#dea136',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#6ed620',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#b820c8',
        landCoverColorAccent: '#026f12',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#326c22',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#db55ad',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#9a4ca0',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#9ea9f2'
      },
      'lunar-delta': {
        waterColor: '#9cd0f0',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#b82cc9',
        forestColorAccent: '#0bf64f',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#7def43',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#d143ff',
        landCoverColorAccent: '#259c53',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#698f3b',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#1c8cd0',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#b379d7',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#c1ea1f'
      },
      'opal-archipelago': {
        waterColor: '#240848',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#20c4e1',
        forestColorAccent: '#537e77',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#95177b',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#f97b57',
        landCoverColorAccent: '#5de4bb',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#c1c763',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#84e408',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#dbc12f',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#f95267'
      },
      'polar-archipelago': {
        waterColor: '#792b7f',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#6123f0',
        forestColorAccent: '#80d390',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#a4309e',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#129e8e',
        landCoverColorAccent: '#8011fc',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#f8ea7c',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#c51b2b',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#f4ee66',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#1c9394'
      },
      'quiet-highlands': {
        waterColor: '#126ae2',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#d6ce0b',
        forestColorAccent: '#d16cbd',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#bf5ddd',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#3fddf1',
        landCoverColorAccent: '#bf6271',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#5b29a9',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#3a7e6a',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#213fc9',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#5b08e5'
      },
      'radiant-archipelago': {
        waterColor: '#2371ed',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#e3e10e',
        forestColorAccent: '#da7dc2',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#c262e4',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#44e4fc',
        landCoverColorAccent: '#c66b7e',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#6630ae',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#478971',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#2648d4',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#6215ee'
      },
      'velvet-delta': {
        waterColor: '#44e8a8',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#c02441',
        forestColorAccent: '#739e17',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#f5b75b',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#995bb7',
        landCoverColorAccent: '#3d045b',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#21a703',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#2444e8',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#7be18f',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#d9f287'
      },
      'wild-archipelago': {
        waterColor: '#77fdc9',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#e75d4a',
        forestColorAccent: '#8ed126',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#fec670',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#a870d8',
        landCoverColorAccent: '#521f82',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#42bc12',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#4b65fd',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#8afcb0',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#ee19a2'
      },
      ...Object.fromEntries([
        ['aero-blue', '#0ea5e9', '#164e63', '#ecfeff', '#cffafe', '#155e75'],
        ['alabaster-coast', '#38bdf8', '#475569', '#fafafa', '#e5e7eb', '#334155'],
        ['amber-harbor', '#0284c7', '#92400e', '#fffbeb', '#fef3c7', '#78350f'],
        ['apricot-bay', '#60a5fa', '#9a3412', '#fff7ed', '#ffedd5', '#7c2d12'],
        ['ash-lagoon', '#2563eb', '#374151', '#f9fafb', '#e5e7eb', '#1f2937'],
        ['birch-inlet', '#7dd3fc', '#3f6212', '#fefce8', '#ecfccb', '#365314'],
        ['blush-marina', '#38bdf8', '#9f1239', '#fff1f2', '#ffe4e6', '#881337'],
        ['bronze-cove', '#0369a1', '#78350f', '#fef3c7', '#fde68a', '#451a03'],
        ['cedar-sound', '#0ea5e9', '#14532d', '#f0fdf4', '#dcfce7', '#052e16'],
        ['clay-shore', '#0284c7', '#9a3412', '#fff7ed', '#fed7aa', '#7c2d12'],
        ['cream-fjord', '#93c5fd', '#57534e', '#fffbeb', '#fef3c7', '#44403c'],
        ['denim-bay', '#1d4ed8', '#1e3a8a', '#eff6ff', '#dbeafe', '#172554'],
        ['eucalyptus-port', '#38bdf8', '#065f46', '#ecfdf5', '#d1fae5', '#064e3b'],
        ['foggy-marina', '#7dd3fc', '#64748b', '#f8fafc', '#e2e8f0', '#475569'],
        ['graphite-coast', '#0284c7', '#1f2937', '#f3f4f6', '#d1d5db', '#111827'],
        ['heather-bay', '#60a5fa', '#6b21a8', '#faf5ff', '#f3e8ff', '#581c87'],
        ['linen-lagoon', '#38bdf8', '#78716c', '#fafaf9', '#e7e5e4', '#57534e'],
        ['mango-inlet', '#0ea5e9', '#b45309', '#fffbeb', '#fde68a', '#92400e'],
        ['mauve-harbor', '#2563eb', '#86198f', '#fdf4ff', '#fae8ff', '#701a75'],
        ['mint-sound', '#7dd3fc', '#047857', '#f0fdfa', '#ccfbf1', '#065f46'],
        ['mossy-cove', '#0284c7', '#365314', '#f7fee7', '#ecfccb', '#3f6212'],
        ['oatmeal-bay', '#60a5fa', '#713f12', '#fefce8', '#fef9c3', '#422006'],
        ['ochre-port', '#0369a1', '#a16207', '#fffbeb', '#fef3c7', '#713f12'],
        ['paper-fjord', '#93c5fd', '#475569', '#ffffff', '#f1f5f9', '#334155'],
        ['peach-coast', '#38bdf8', '#c2410c', '#fff7ed', '#ffedd5', '#9a3412'],
        ['pine-marina', '#0ea5e9', '#14532d', '#f0fdf4', '#bbf7d0', '#166534'],
        ['plum-inlet', '#2563eb', '#581c87', '#faf5ff', '#e9d5ff', '#3b0764'],
        ['porcelain-bay', '#7dd3fc', '#334155', '#f8fafc', '#e0f2fe', '#1e293b'],
        ['rosewood-port', '#0284c7', '#881337', '#fff1f2', '#fecdd3', '#4c0519'],
        ['sage-harbor', '#60a5fa', '#3f6212', '#f7fee7', '#d9f99d', '#365314'],
        ['sandstone-sound', '#0ea5e9', '#92400e', '#fffbeb', '#fed7aa', '#78350f'],
        ['seafoam-coast', '#38bdf8', '#0f766e', '#f0fdfa', '#99f6e4', '#134e4a'],
        ['shell-lagoon', '#7dd3fc', '#be123c', '#fff1f2', '#ffe4e6', '#9f1239'],
        ['smoke-bay', '#2563eb', '#475569', '#f8fafc', '#cbd5e1', '#334155'],
        ['spruce-inlet', '#0284c7', '#064e3b', '#ecfdf5', '#a7f3d0', '#022c22'],
        ['stone-marina', '#60a5fa', '#44403c', '#fafaf9', '#d6d3d1', '#292524'],
        ['terracotta-cove', '#0ea5e9', '#9a3412', '#fff7ed', '#fdba74', '#7c2d12'],
        ['thistle-shore', '#38bdf8', '#7e22ce', '#faf5ff', '#e9d5ff', '#6b21a8'],
        ['umber-bay', '#0369a1', '#78350f', '#fef3c7', '#d6d3d1', '#451a03'],
        ['vanilla-port', '#93c5fd', '#854d0e', '#fefce8', '#fef9c3', '#713f12'],
        ['willow-fjord', '#7dd3fc', '#4d7c0f', '#f7fee7', '#d9f99d', '#3f6212'],
        ['winter-harbor', '#1d4ed8', '#475569', '#f8fafc', '#e0f2fe', '#334155'],
        ['wisteria-coast', '#60a5fa', '#6d28d9', '#f5f3ff', '#ddd6fe', '#5b21b6'],
        ['woodland-bay', '#0284c7', '#166534', '#f0fdf4', '#bbf7d0', '#14532d'],
        ['zinc-marina', '#38bdf8', '#52525b', '#fafafa', '#e4e4e7', '#3f3f46'],
        ['cocoa-inlet', '#0ea5e9', '#78350f', '#fdf8f6', '#e7d8cf', '#4b2e24'],
        ['coral-harbor', '#60a5fa', '#be123c', '#fff1f2', '#fecdd3', '#9f1239'],
        ['fern-coast', '#38bdf8', '#047857', '#ecfdf5', '#a7f3d0', '#065f46'],
        ['lilac-bay', '#7dd3fc', '#7e22ce', '#faf5ff', '#f3e8ff', '#6b21a8'],
        ['pebble-port', '#0284c7', '#57534e', '#fafaf9', '#e7e5e4', '#44403c']
      ].map(([name, waterColor, forestColor, landColor, landCoverColor, roadColor]) => [
        name,
        {
          waterColor, waterOpacity: '100', waterToggle: true,
          forestColor, forestColorAccent: forestColor, forestOpacity: '100', forestToggle: true,
          landColor, landOpacity: '100', landToggle: true,
          landCoverColor, landCoverColorAccent: landCoverColor, landCoverOpacity: '100', landCoverToggle: true,
          roadColor, roadOpacity: '100', roadToggle: true,
          boundaryColor: roadColor, boundaryOpacity: '100', boundaryToggle: true,
          buildingColor: landCoverColor, buildingOpacity: '100', buildingToggle: true,
          buildingOutlineToggle: true, buildingOutlineColor: roadColor
        }
      ]))

};

// End of preset catalogue and color definitions.
