// =============================================================================
// cartiva - preset-data.js (preset catalogue and color definitions)
// =============================================================================


// -----------------------------------------------------------------------------
// Preset catalogue
// -----------------------------------------------------------------------------
// Display metadata used to populate the preset selector.
window.CartivaPresetCatalog = [
  {
    id: 'alpine',
    name: 'Alpine Snow'
  },
  {
    id: 'amethyst',
    name: 'Amethyst Glow'
  },
  {
    id: 'arctic-badlands',
    name: 'Arctic Badlands'
  },
  {
    id: 'blueprint',
    name: 'Blueprint / Technical'
  },
  {
    id: 'burnished-delta',
    name: 'Burnished Delta'
  },
  {
    id: 'canyon',
    name: 'Canyon Red Rock'
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard Dark'
  },
  {
    id: 'cherry',
    name: 'Cherry Blossom'
  },
  {
    id: 'cloud-delta',
    name: 'Cloud Delta'
  },
  {
    id: 'cloud-highlands',
    name: 'Cloud Highlands'
  },
  {
    id: 'cobalt',
    name: 'Cobalt Spark'
  },
  {
    id: 'coffee',
    name: 'Coffee and Cream'
  },
  {
    id: 'copper',
    name: 'Copper Patina'
  },
  {
    id: 'coral',
    name: 'Coral Reef'
  },
  {
    id: 'crimson',
    name: 'Crimson Night'
  },
  {
    id: 'cyberalt',
    name: 'Cyberpunk Neon Alt'
  },
  {
    id: 'darkmode',
    name: 'Dark Mode / Neon'
  },
  {
    id: 'deep-archipelago',
    name: 'Deep Archipelago'
  },
  {
    id: 'electric-highlands',
    name: 'Electric Highlands'
  },
  {
    id: 'fiesta',
    name: 'Fiesta Vibrant'
  },
  {
    id: 'frostbite',
    name: 'Frostbite Blue'
  },
  {
    id: 'galaxy',
    name: 'Galaxy Deep'
  },
  {
    id: 'ice',
    name: 'Glacial Ice'
  },
  {
    id: 'granite',
    name: 'Granite Stone'
  },
  {
    id: 'hazelnut',
    name: 'Hazelnut Earth'
  },
  {
    id: 'horizon',
    name: 'Horizon Line'
  },
  {
    id: 'indigo',
    name: 'Indigo Night'
  },
  {
    id: 'jungle',
    name: 'Jungle Safari'
  },
  {
    id: 'lagoon',
    name: 'Lagoon Teal'
  },
  {
    id: 'magma',
    name: 'Magma Dark'
  },
  {
    id: 'matrix',
    name: 'Matrix Green'
  },
  {
    id: 'midnight',
    name: 'Midnight Purple'
  },
  {
    id: 'mocha',
    name: 'Mocha Roast'
  },
  {
    id: 'nebula',
    name: 'Nebula Glow'
  },
  {
    id: 'nordic',
    name: 'Nordic Frost'
  },
  {
    id: 'olive',
    name: 'Olive Grove'
  },
  {
    id: 'opal-archipelago',
    name: 'Opal Archipelago'
  },
  {
    id: 'pasteldream',
    name: 'Pastel Dream'
  },
  {
    id: 'peacock',
    name: 'Peacock Feather'
  },
  {
    id: 'polar-archipelago',
    name: 'Polar Archipelago'
  },
  {
    id: 'monochrome',
    name: 'Pure Monochrome'
  },
  {
    id: 'quartz',
    name: 'Quartz Crystal'
  },
  {
    id: 'quiet-highlands',
    name: 'Quiet Highlands'
  },
  {
    id: 'redwood',
    name: 'Redwood Timber'
  },
  {
    id: 'slate',
    name: 'Slate Minimal'
  },
  {
    id: 'solarized',
    name: 'Solarized Light'
  },
  {
    id: 'steampunk',
    name: 'Steampunk Brass'
  },
  {
    id: 'synthwave',
    name: 'Synthwave 80s'
  },
  {
    id: 'tundra',
    name: 'Tundra Frost'
  },
  {
    id: 'warmvintage',
    name: 'Warm Vintage Sepia'
  },
  {
    id: 'aero-blue',
    name: 'Aero Blue'
  },
  {
    id: 'alabaster-coast',
    name: 'Alabaster Coast'
  },
  {
    id: 'birch-inlet',
    name: 'Birch Inlet'
  },
  {
    id: 'bronze-cove',
    name: 'Bronze Cove'
  },
  {
    id: 'cedar-sound',
    name: 'Cedar Sound'
  },
  {
    id: 'cream-fjord',
    name: 'Cream Fjord'
  },
  {
    id: 'eucalyptus-port',
    name: 'Eucalyptus Port'
  },
  {
    id: 'foggy-marina',
    name: 'Foggy Marina'
  },
  {
    id: 'graphite-coast',
    name: 'Graphite Coast'
  },
  {
    id: 'linen-lagoon',
    name: 'Linen Lagoon'
  },
  {
    id: 'mauve-harbor',
    name: 'Mauve Harbor'
  },
  {
    id: 'mossy-cove',
    name: 'Mossy Cove'
  },
  {
    id: 'oatmeal-bay',
    name: 'Oatmeal Bay'
  },
  {
    id: 'paper-fjord',
    name: 'Paper Fjord'
  },
  {
    id: 'peach-coast',
    name: 'Peach Coast'
  },
  {
    id: 'porcelain-bay',
    name: 'Porcelain Bay'
  },
  {
    id: 'rosewood-port',
    name: 'Rosewood Port'
  },
  {
    id: 'sage-harbor',
    name: 'Sage Harbor'
  },
  {
    id: 'sandstone-sound',
    name: 'Sandstone Sound'
  },
  {
    id: 'spruce-inlet',
    name: 'Spruce Inlet'
  },
  {
    id: 'stone-marina',
    name: 'Stone Marina'
  },
  {
    id: 'terracotta-cove',
    name: 'Terracotta Cove'
  },
  {
    id: 'thistle-shore',
    name: 'Thistle Shore'
  },
  {
    id: 'umber-bay',
    name: 'Umber Bay'
  },
  {
    id: 'zinc-marina',
    name: 'Zinc Marina'
  },
  {
    id: 'cocoa-inlet',
    name: 'Cocoa Inlet'
  },
  {
    id: 'coral-harbor',
    name: 'Coral Harbor'
  },
  {
    id: 'kandinsky',
    name: 'Kandinsky'
  },
  {
    id: 'schwarzlicht',
    name: 'Schwarzlicht'
  },
  {
    id: 'testei',
    name: 'testei'
  }
];


// -----------------------------------------------------------------------------
// Preset color definitions
// -----------------------------------------------------------------------------
// Each preset maps UI control IDs to colors, opacity values, and visibility flags.
// Preset definitions are kept in one shared object so the UI and rendering
// logic can use the same values without duplicating color settings.
window.CartivaPresetData = {

      'darkmode': {
        waterColor: '#1e3a8a', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#064e3b', 
		forestColorAccent: '#065f46', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#111827', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#1f2937', 
		landCoverColorAccent: '#374151', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#9ca3af', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#4b5563', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#374151', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#6b7280'
      },
      'kandinsky': {
        waterColor: '#4cc9f0', 
		waterwayColor: '#0077b6', 
		waterShadowColor: '#4361ee', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#2a9d8f', 
		forestColorAccent: '#f4d35e', 
		parkColor: '#f4d35e', 
		natureReserveColor: '#43aa8b', 
		grassColor: '#90be6d', 
		woodColor: '#277da1', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#f7e7c6', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#f2a65a', 
		landCoverColorAccent: '#e76f51', 
		residentialColor: '#e76f51', 
		cemeteryColor: '#8ac926', 
		stadiumColor: '#ffca3a', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#263238', 
		roadCaseColor: '#f7e7c6', 
		motorwayColor: '#e63946', 
		trunkRoadColor: '#f77f00', 
		primaryRoadColor: '#ffca3a', 
		secondaryRoadColor: '#1982c4', 
		minorRoadColor: '#6a4c93', 
		serviceRoadColor: '#495057', 
		pathColor: '#2a9d8f', 
		railColor: '#8338ec', 
		bridgeColor: '#ffffff', 
		bridgeCaseColor: '#1d3557', 
		tunnelColor: '#6c757d', 
		tunnelCaseColor: '#212529', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#6a4c93', 
		countryBoundaryColor: '#1d3557', 
		stateBoundaryColor: '#8338ec', 
		countyBoundaryColor: '#1982c4', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#ffadad', 
		buildingTopColor: '#ff6b6b', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#1d3557'
      },
      'schwarzlicht': {
        waterColor: '#00d5ff', 
		waterwayColor: '#6dfcff', 
		waterShadowColor: '#191970', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#00c46a', 
		forestColorAccent: '#00ff9c', 
		parkColor: '#00ff9c', 
		natureReserveColor: '#16f7d2', 
		grassColor: '#35ff7d', 
		woodColor: '#008f5a', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#090012', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#140022', 
		landCoverColorAccent: '#2b1648', 
		residentialColor: '#2b1648', 
		cemeteryColor: '#8cff66', 
		stadiumColor: '#ffea00', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#ffffff', 
		roadCaseColor: '#24003d', 
		motorwayColor: '#ff2fd6', 
		motorwayCaseColor: '#ff00aa', 
		trunkRoadColor: '#ff7a00', 
		primaryRoadColor: '#fff000', 
		secondaryRoadColor: '#00f0ff', 
		minorRoadColor: '#ffffff', 
		serviceRoadColor: '#9bfffc', 
		pathColor: '#73ff66', 
		railColor: '#ff66ff', 
		bridgeColor: '#ffffff', 
		bridgeCaseColor: '#ffcc00', 
		tunnelColor: '#6b5cff', 
		tunnelCaseColor: '#270045', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#5ffcff', 
		countryBoundaryColor: '#ffffff', 
		stateBoundaryColor: '#ff4fd8', 
		countyBoundaryColor: '#5ffcff', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#19002f', 
		buildingTopColor: '#ff4fd8', 
		buildingOpacity: '95', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#ffffff'
      },
	  'testei': {
        waterColor: '#6e9adb', waterwayColor: '#4f6e9c', waterShadowColor: '#6e9adb', waterOpacity: '100', waterToggle: true,
        forestColor: '#509648', forestColorAccent: '#3f7538', parkColor: '#509648', natureReserveColor: '#509648', grassColor: '#67b05f', woodColor: '#4cb83e', forestOpacity: '100', forestToggle: true,
        landColor: '#f1f0f2', landOpacity: '100', landToggle: true,
        landCoverColor: '#bebdbf', landCoverColorAccent: '#bebdbf', residentialColor: '#bebdbf', cemeteryColor: '#bebdbf', stadiumColor: '#bebdbf', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#3d3d3d', roadCaseColor: '#3d3d3d', motorwayColor: '#3d3d3d', motorwayCaseColor: '#3d3d3d', trunkRoadColor: '#3d3d3d', primaryRoadColor: '#3d3d3d', secondaryRoadColor: '#3d3d3d', minorRoadColor: '#3d3d3d', serviceRoadColor: '#3d3d3d', pathColor: '#3d3d3d', railColor: '#3d3d3d', bridgeColor: '#3d3d3d', bridgeCaseColor: '#3d3d3d', tunnelColor: '#3d3d3d', tunnelCaseColor: '#3d3d3d', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#5ffcff', countryBoundaryColor: '#595757', stateBoundaryColor: '#8f2222', countyBoundaryColor: '#5ffcff', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#969595', buildingTopColor: '#969595', buildingOpacity: '95', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#3d3d3d'
      },
      'blueprint': {
        waterColor: '#1d4ed8', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#1e40af', 
		forestColorAccent: '#2563eb', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#0f172a', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#1e293b', 
		landCoverColorAccent: '#334155', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#60a5fa', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#93c5fd', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#1e3a8a', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#93c5fd'
      },
      'warmvintage': {
        waterColor: '#93c5fd', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#d1fae5', 
		forestColorAccent: '#a7f3d0', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#fdf6e2', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#faedcd', 
		landCoverColorAccent: '#fefae0', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#bc6c25', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#dda15e', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#e9d8a6', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#dda15e'
      },
      'midnight': {
        waterColor: '#6366f1', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#312e81', 
		forestColorAccent: '#3730a3', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#030712', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#111827', 
		landCoverColorAccent: '#1f2937', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#a5b4fc', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#4f46e5', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#1e1b4b',
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#818cf8'
      },
      'cyberalt': {
        waterColor: '#22d3ee', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#a21caf', 
		forestColorAccent: '#c084fc', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#09090b', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#18181b', 
		landCoverColorAccent: '#27272a', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#f43f5e', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#a855f7', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#27272a', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#22d3ee'
      },
      'pasteldream': {
        waterColor: '#bae6fd', waterOpacity: '100', waterToggle: true,
        forestColor: '#fed7aa', forestColorAccent: '#ffedd5', forestOpacity: '100', forestToggle: true,
        landColor: '#fdf4ff', landOpacity: '100', landToggle: true,
        landCoverColor: '#fae8ff', landCoverColorAccent: '#f5d0fe', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#c084fc', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#e879f9', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#f5d0fe', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#e879f9'
      },
      'nordic': {
        waterColor: '#0284c7', waterOpacity: '100', waterToggle: true,
        forestColor: '#334155', forestColorAccent: '#475569', forestOpacity: '100', forestToggle: true,
        landColor: '#f1f5f9', landOpacity: '100', landToggle: true,
        landCoverColor: '#e2e8f0', landCoverColorAccent: '#cbd5e1', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#0f172a', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#64748b', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#cbd5e1', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#94a3b8'
      },
      'cherry': {
        waterColor: '#7dd3fc', waterOpacity: '100', waterToggle: true,
        forestColor: '#fda4af', forestColorAccent: '#fecdd3', forestOpacity: '100', forestToggle: true,
        landColor: '#fff1f2', landOpacity: '100', landToggle: true,
        landCoverColor: '#ffe4e6', landCoverColorAccent: '#fecdd3', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#9f1239', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#fb7185', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fecdd3', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#f43f5e'
      },
      'coffee': {
        waterColor: '#7dd3fc', waterOpacity: '100', waterToggle: true,
        forestColor: '#78350f', forestColorAccent: '#92400e', forestOpacity: '100', forestToggle: true,
        landColor: '#fef3c7', landOpacity: '100', landToggle: true,
        landCoverColor: '#fde68a', landCoverColorAccent: '#fcd34d', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#451a03', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#b45309', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fcd34d', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#92400e'
      },
      'synthwave': {
        waterColor: '#ff007f', waterOpacity: '100', waterToggle: true,
        forestColor: '#7928ca', forestColorAccent: '#8a2be2', forestOpacity: '100', forestToggle: true,
        landColor: '#120428', landOpacity: '100', landToggle: true,
        landCoverColor: '#1a0b36', landCoverColorAccent: '#2b1055', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#00f0ff', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#ff007f', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#2b1055', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#00f0ff'
      },
      'olive': {
        waterColor: '#60a5fa', waterOpacity: '100', waterToggle: true,
        forestColor: '#365314', forestColorAccent: '#3f6212', forestOpacity: '100', forestToggle: true,
        landColor: '#fefce8', landOpacity: '100', landToggle: true,
        landCoverColor: '#fef08a', landCoverColorAccent: '#fde047', landCoverOpacity: '100', landCoverToggle: true,
        roadColor: '#1a2e05', roadOpacity: '100', roadToggle: true,
        boundaryColor: '#65a30d', boundaryOpacity: '100', boundaryToggle: true,
        buildingColor: '#fde047', buildingOpacity: '100', buildingToggle: true,
        buildingOutlineToggle: true, buildingOutlineColor: '#4d7c0f'
      },
      'crimson': {
        waterColor: '#38bdf8', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#881337', 
		forestColorAccent: '#9f1239', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#fff1f2', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#ffe4e6', 
		landCoverColorAccent: '#fecdd3', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#4c0519', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#e11d48', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#fecdd3', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#be123c'
      },
      'solarized': {
        waterColor: '#268bd2', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#859900', 
		forestColorAccent: '#b58900', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#fdf6e3', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#eee8d5', 
		landCoverColorAccent: '#93a1a1', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#cb4b16', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#657b83', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#eee8d5', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#839496'
      },
      'matrix': {
        waterColor: '#004d40', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#003300', 
		forestColorAccent: '#004400', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#000d08', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#001a12', 
		landCoverColorAccent: '#002b1d', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#00ff66', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#008f53', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#002b1d', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#00ff66'
      },
      'coral': {
        waterColor: '#0284c7', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#f43f5e', 
		forestColorAccent: '#fb7185', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#fffaf0', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#ffedd5', 
		landCoverColorAccent: '#fed7aa', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#9a3412', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#fb923c', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#fed7aa', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#f97316'
      },
      'slate': {
        waterColor: '#38bdf8', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#475569', 
		forestColorAccent: '#64748b', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#0f172a', 
		landOpacity: '100', landToggle: true,
        landCoverColor: '#1e293b', 
		landCoverColorAccent: '#334155', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#e2e8f0', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#475569', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#334155', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#94a3b8'
      },
      'ice': {
        waterColor: '#0284c7', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#7dd3fc', 
		forestColorAccent: '#bae6fd', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#f0fdf4', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#e0f2fe', 
		landCoverColorAccent: '#bae6fd', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#0369a1', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#38bdf8', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#bae6fd', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#0284c7'
      },
      'magma': {
        waterColor: '#3b82f6', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#9a3412', 
		forestColorAccent: '#c2410c', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#1c1917', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#292524', 
		landCoverColorAccent: '#44403c', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#f97316', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#ea580c', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#44403c', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#fb923c'
      },
      'steampunk': {
        waterColor: '#0284c7', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#78350f', 
		forestColorAccent: '#92400e', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#292524', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#44403c', 
		landCoverColorAccent: '#57534e', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#d97706', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#b45309', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#57534e', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#f59e0b'
      },
      'amethyst': {
        waterColor: '#38bdf8', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#581c87', 
		forestColorAccent: '#6b21a8', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#2e1065', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#3b0764', 
		landCoverColorAccent: '#581c87', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#c084fc', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#9333ea', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#581c87', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#d8b4fe'
      },
      'monochrome': {
        waterColor: '#000000', 
		waterOpacity: '100', 
		waterToggle: true,
        forestColor: '#333333', 
		forestColorAccent: '#666666', 
		forestOpacity: '100', 
		forestToggle: true,
        landColor: '#ffffff', 
		landOpacity: '100', 
		landToggle: true,
        landCoverColor: '#f2f2f2', 
		landCoverColorAccent: '#e6e6e6', 
		landCoverOpacity: '100', 
		landCoverToggle: true,
        roadColor: '#000000', 
		roadOpacity: '100', 
		roadToggle: true,
        boundaryColor: '#000000', 
		boundaryOpacity: '100', 
		boundaryToggle: true,
        buildingColor: '#cccccc', 
		buildingOpacity: '100', 
		buildingToggle: true,
        buildingOutlineToggle: true, 
		buildingOutlineColor: '#000000'
      },
      'alpine': {
        waterColor: '#7dd3fc',
        forestColor: '#475569',
        forestColorAccent: '#475569',
        landColor: '#f8fafc',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#1e293b',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'canyon': {
        waterColor: '#0284c7',
        forestColor: '#9a3412',
        forestColorAccent: '#9a3412',
        landColor: '#fff7ed',
        landCoverColor: '#ffedd5',
        landCoverColorAccent: '#ffedd5',
        roadColor: '#7c2d12',
        boundaryColor: '#ea580c',
        buildingColor: '#fed7aa',
        buildingOutlineColor: '#c2410c',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'chalkboard': {
        waterColor: '#38bdf8',
        forestColor: '#334155',
        forestColorAccent: '#334155',
        landColor: '#1e293b',
        landCoverColor: '#334155',
        landCoverColorAccent: '#334155',
        roadColor: '#f8fafc',
        boundaryColor: '#64748b',
        buildingColor: '#475569',
        buildingOutlineColor: '#94a3b8',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'cobalt': {
        waterColor: '#60a5fa',
        forestColor: '#1e3a8a',
        forestColorAccent: '#1e3a8a',
        landColor: '#eff6ff',
        landCoverColor: '#dbeafe',
        landCoverColorAccent: '#dbeafe',
        roadColor: '#172554',
        boundaryColor: '#3b82f6',
        buildingColor: '#bfdbfe',
        buildingOutlineColor: '#2563eb',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'copper': {
        waterColor: '#0284c7',
        forestColor: '#78350f',
        forestColorAccent: '#78350f',
        landColor: '#292524',
        landCoverColor: '#44403c',
        landCoverColorAccent: '#44403c',
        roadColor: '#fb923c',
        boundaryColor: '#d97706',
        buildingColor: '#57534e',
        buildingOutlineColor: '#f59e0b',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'cosmic': {
        waterColor: '#ec4899',
        forestColor: '#6b21a8',
        forestColorAccent: '#6b21a8',
        landColor: '#090514',
        landCoverColor: '#1e1b4b',
        landCoverColorAccent: '#1e1b4b',
        roadColor: '#38bdf8',
        boundaryColor: '#a855f7',
        buildingColor: '#312e81',
        buildingOutlineColor: '#c084fc',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'dusk': {
        waterColor: '#f43f5e',
        forestColor: '#4c1d95',
        forestColorAccent: '#4c1d95',
        landColor: '#1e1b4b',
        landCoverColor: '#312e81',
        landCoverColorAccent: '#312e81',
        roadColor: '#fcd34d',
        boundaryColor: '#8b5cf6',
        buildingColor: '#3730a3',
        buildingOutlineColor: '#a78bfa',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'fiesta': {
        waterColor: '#06b6d4',
        forestColor: '#f43f5e',
        forestColorAccent: '#f43f5e',
        landColor: '#fffbeb',
        landCoverColor: '#fef3c7',
        landCoverColorAccent: '#fef3c7',
        roadColor: '#b91c1c',
        boundaryColor: '#f59e0b',
        buildingColor: '#fde68a',
        buildingOutlineColor: '#d97706',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'frostbite': {
        waterColor: '#38bdf8',
        forestColor: '#0284c7',
        forestColorAccent: '#0284c7',
        landColor: '#f0f9ff',
        landCoverColor: '#e0f2fe',
        landCoverColorAccent: '#e0f2fe',
        roadColor: '#0c4a6e',
        boundaryColor: '#0ea5e9',
        buildingColor: '#bae6fd',
        buildingOutlineColor: '#0284c7',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'galaxy': {
        waterColor: '#3b82f6',
        forestColor: '#581c87',
        forestColorAccent: '#581c87',
        landColor: '#030712',
        landCoverColor: '#0f172a',
        landCoverColorAccent: '#0f172a',
        roadColor: '#f43f5e',
        boundaryColor: '#8b5cf6',
        buildingColor: '#1e1b4b',
        buildingOutlineColor: '#a855f7',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'granite': {
        waterColor: '#475569',
        forestColor: '#334155',
        forestColorAccent: '#334155',
        landColor: '#f1f5f9',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#0f172a',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'hazelnut': {
        waterColor: '#38bdf8',
        forestColor: '#78350f',
        forestColorAccent: '#78350f',
        landColor: '#fdf8f6',
        landCoverColor: '#f5ebe0',
        landCoverColorAccent: '#f5ebe0',
        roadColor: '#432818',
        boundaryColor: '#b08968',
        buildingColor: '#d5bdaf',
        buildingOutlineColor: '#9c6644',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'horizon': {
        waterColor: '#0284c7',
        forestColor: '#0f172a',
        forestColorAccent: '#0f172a',
        landColor: '#f8fafc',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#334155',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'indigo': {
        waterColor: '#38bdf8',
        forestColor: '#3730a3',
        forestColorAccent: '#3730a3',
        landColor: '#eef2ff',
        landCoverColor: '#e0e7ff',
        landCoverColorAccent: '#e0e7ff',
        roadColor: '#312e81',
        boundaryColor: '#6366f1',
        buildingColor: '#c7d2fe',
        buildingOutlineColor: '#4f46e5',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'jungle': {
        waterColor: '#38bdf8',
        forestColor: '#14532d',
        forestColorAccent: '#14532d',
        landColor: '#f0fdf4',
        landCoverColor: '#dcfce7',
        landCoverColorAccent: '#dcfce7',
        roadColor: '#052e16',
        boundaryColor: '#15803d',
        buildingColor: '#bbf7d0',
        buildingOutlineColor: '#16a34a',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'lagoon': {
        waterColor: '#0284c7',
        forestColor: '#0f766e',
        forestColorAccent: '#0f766e',
        landColor: '#f0fdfa',
        landCoverColor: '#ccfbf1',
        landCoverColorAccent: '#ccfbf1',
        roadColor: '#134e4a',
        boundaryColor: '#14b8a6',
        buildingColor: '#99f6e4',
        buildingOutlineColor: '#0d9488',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'mocha': {
        waterColor: '#7dd3fc',
        forestColor: '#5c4033',
        forestColorAccent: '#5c4033',
        landColor: '#f5deb3',
        landCoverColor: '#deb887',
        landCoverColorAccent: '#deb887',
        roadColor: '#3e2723',
        boundaryColor: '#8b4513',
        buildingColor: '#d2b48c',
        buildingOutlineColor: '#a0522d',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'nebula': {
        waterColor: '#ec4899',
        forestColor: '#9333ea',
        forestColorAccent: '#9333ea',
        landColor: '#0f051d',
        landCoverColor: '#1e0c38',
        landCoverColorAccent: '#1e0c38',
        roadColor: '#22d3ee',
        boundaryColor: '#c084fc',
        buildingColor: '#2e1065',
        buildingOutlineColor: '#d8b4fe',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'peacock': {
        waterColor: '#38bdf8',
        forestColor: '#047857',
        forestColorAccent: '#047857',
        landColor: '#ecfdf5',
        landCoverColor: '#d1fae5',
        landCoverColorAccent: '#d1fae5',
        roadColor: '#064e3b',
        boundaryColor: '#10b981',
        buildingColor: '#a7f3d0',
        buildingOutlineColor: '#059669',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'quartz': {
        waterColor: '#7dd3fc',
        forestColor: '#cbd5e1',
        forestColorAccent: '#cbd5e1',
        landColor: '#f8fafc',
        landCoverColor: '#f1f5f9',
        landCoverColorAccent: '#f1f5f9',
        roadColor: '#334155',
        boundaryColor: '#94a3b8',
        buildingColor: '#e2e8f0',
        buildingOutlineColor: '#cbd5e1',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'redwood': {
        waterColor: '#38bdf8',
        forestColor: '#7f1d1d',
        forestColorAccent: '#7f1d1d',
        landColor: '#fef2f2',
        landCoverColor: '#fee2e2',
        landCoverColorAccent: '#fee2e2',
        roadColor: '#450a0a',
        boundaryColor: '#dc2626',
        buildingColor: '#fecaca',
        buildingOutlineColor: '#b91c1c',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'tundra': {
        waterColor: '#38bdf8',
        forestColor: '#475569',
        forestColorAccent: '#475569',
        landColor: '#f1f5f9',
        landCoverColor: '#e2e8f0',
        landCoverColorAccent: '#e2e8f0',
        roadColor: '#1e293b',
        boundaryColor: '#64748b',
        buildingColor: '#cbd5e1',
        buildingOutlineColor: '#475569',
        waterOpacity: '100',
        forestOpacity: '100',
        landOpacity: '100',
        landCoverOpacity: '100',
        roadOpacity: '100',
        boundaryOpacity: '100',
        buildingOpacity: '100',
        waterToggle: true,
        forestToggle: true,
        landToggle: true,
        landCoverToggle: true,
        roadToggle: true,
        boundaryToggle: true,
        buildingToggle: true,
        buildingOutlineToggle: true
      },
      'arctic-badlands': {
        waterColor: '#396bbf',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#216330',
        forestColorAccent: '#409350',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#e4f0de',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#d2dece',
        landCoverColorAccent: '#c0d1bc',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#382a3c',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#855b6b',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#b4aea6',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#5c5354'
      },
      'burnished-delta': {
        waterColor: '#38bdf8',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#b03451',
        forestColorAccent: '#a34e87',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#05272b',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#092b47',
        landCoverColorAccent: '#0d344b',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#b17773',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#14d4b8',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#eb111f',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#a9e2b7'
      },
      'cloud-delta': {
        waterColor: '#93c5fd',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#f19360',
        forestColorAccent: '#d0a3a0',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#14404e',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#224e7e',
        landCoverColorAccent: '#30618c',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#e89a8c',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#550bdb',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#043e56',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#cc23e4'
      },
      'cloud-highlands': {
        waterColor: '#38bdf8',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#0bb966',
        forestColorAccent: '#e2c5aa',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#1a4a5c',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#2c5c94',
        landCoverColorAccent: '#3e73a6',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#fea896',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#6f21e9',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#0e506c',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#da3df6'
      },
      'deep-archipelago': {
        waterColor: '#1e3a8a',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#18cc69',
        forestColorAccent: '#ebd6af',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#1d4f63',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#31639f',
        landCoverColorAccent: '#457cb3',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#09af9b',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#7c2cf0',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#135977',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#e14aff'
      },
      'electric-highlands': {
        waterColor: '#152ff3',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#8d7784',
        forestColorAccent: '#3c6fdc',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#387ca2',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#5ea202',
        landCoverColorAccent: '#84cd28',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#6ceec8',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#f18f2f',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#40aada',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#20bf50'
      },
      'opal-archipelago': {
        waterColor: '#240848',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#20c4e1',
        forestColorAccent: '#537e77',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#95177b',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#f97b57',
        landCoverColorAccent: '#5de4bb',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#c1c763',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#84e408',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#dbc12f',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#f95267'
      },
      'polar-archipelago': {
        waterColor: '#792b7f',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#6123f0',
        forestColorAccent: '#80d390',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#a4309e',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#129e8e',
        landCoverColorAccent: '#8011fc',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#f8ea7c',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#c51b2b',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#f4ee66',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#1c9394'
      },
      'quiet-highlands': {
        waterColor: '#126ae2',
        waterOpacity: '100',
        waterToggle: true,
        forestColor: '#d6ce0b',
        forestColorAccent: '#d16cbd',
        forestOpacity: '100',
        forestToggle: true,
        landColor: '#bf5ddd',
        landOpacity: '100',
        landToggle: true,
        landCoverColor: '#3fddf1',
        landCoverColorAccent: '#bf6271',
        landCoverOpacity: '100',
        landCoverToggle: true,
        roadColor: '#5b29a9',
        roadOpacity: '100',
        roadToggle: true,
        boundaryColor: '#3a7e6a',
        boundaryOpacity: '100',
        boundaryToggle: true,
        buildingColor: '#213fc9',
        buildingOpacity: '100',
        buildingToggle: true,
        buildingOutlineToggle: true,
        buildingOutlineColor: '#5b08e5'
      },
      ...Object.fromEntries([
        ['aero-blue', '#0ea5e9', '#164e63', '#ecfeff', '#cffafe', '#155e75'],
        ['alabaster-coast', '#38bdf8', '#475569', '#fafafa', '#e5e7eb', '#334155'],
        ['birch-inlet', '#7dd3fc', '#3f6212', '#fefce8', '#ecfccb', '#365314'],
        ['bronze-cove', '#0369a1', '#78350f', '#fef3c7', '#fde68a', '#451a03'],
        ['cedar-sound', '#0ea5e9', '#14532d', '#f0fdf4', '#dcfce7', '#052e16'],
        ['cream-fjord', '#93c5fd', '#57534e', '#fffbeb', '#fef3c7', '#44403c'],
        ['eucalyptus-port', '#38bdf8', '#065f46', '#ecfdf5', '#d1fae5', '#064e3b'],
        ['foggy-marina', '#7dd3fc', '#64748b', '#f8fafc', '#e2e8f0', '#475569'],
        ['graphite-coast', '#0284c7', '#1f2937', '#f3f4f6', '#d1d5db', '#111827'],
        ['linen-lagoon', '#38bdf8', '#78716c', '#fafaf9', '#e7e5e4', '#57534e'],
        ['mauve-harbor', '#2563eb', '#86198f', '#fdf4ff', '#fae8ff', '#701a75'],
        ['mossy-cove', '#0284c7', '#365314', '#f7fee7', '#ecfccb', '#3f6212'],
        ['oatmeal-bay', '#60a5fa', '#713f12', '#fefce8', '#fef9c3', '#422006'],
        ['paper-fjord', '#93c5fd', '#475569', '#ffffff', '#f1f5f9', '#334155'],
        ['peach-coast', '#38bdf8', '#c2410c', '#fff7ed', '#ffedd5', '#9a3412'],
        ['porcelain-bay', '#7dd3fc', '#334155', '#f8fafc', '#e0f2fe', '#1e293b'],
        ['rosewood-port', '#0284c7', '#881337', '#fff1f2', '#fecdd3', '#4c0519'],
        ['sage-harbor', '#60a5fa', '#3f6212', '#f7fee7', '#d9f99d', '#365314'],
        ['sandstone-sound', '#0ea5e9', '#92400e', '#fffbeb', '#fed7aa', '#78350f'],
        ['spruce-inlet', '#0284c7', '#064e3b', '#ecfdf5', '#a7f3d0', '#022c22'],
        ['stone-marina', '#60a5fa', '#44403c', '#fafaf9', '#d6d3d1', '#292524'],
        ['terracotta-cove', '#0ea5e9', '#9a3412', '#fff7ed', '#fdba74', '#7c2d12'],
        ['thistle-shore', '#38bdf8', '#7e22ce', '#faf5ff', '#e9d5ff', '#6b21a8'],
        ['umber-bay', '#0369a1', '#78350f', '#fef3c7', '#d6d3d1', '#451a03'],
        ['zinc-marina', '#38bdf8', '#52525b', '#fafafa', '#e4e4e7', '#3f3f46'],
        ['cocoa-inlet', '#0ea5e9', '#78350f', '#fdf8f6', '#e7d8cf', '#4b2e24'],
        ['coral-harbor', '#60a5fa', '#be123c', '#fff1f2', '#fecdd3', '#9f1239']
      ].map(([name, waterColor, forestColor, landColor, landCoverColor, roadColor]) => [
        name,
        {
          waterColor, waterOpacity: '100', waterToggle: true,
          forestColor, forestColorAccent: forestColor, forestOpacity: '100', forestToggle: true,
          landColor, landOpacity: '100', landToggle: true,
          landCoverColor, landCoverColorAccent: landCoverColor, landCoverOpacity: '100', landCoverToggle: true,
          roadColor, roadOpacity: '100', roadToggle: true,
          boundaryColor: roadColor, boundaryOpacity: '100', boundaryToggle: true,
          buildingColor: landCoverColor, buildingOpacity: '100', buildingToggle: true,
          buildingOutlineToggle: true, buildingOutlineColor: roadColor
        }
      ]))

};

// End of preset catalogue and color definitions.
