# About: This action ensures that the latest github release gets pushed to github-pages https://yafp.github.io/cartiva/ - to act as demo
#
name: Deploy Release to GitHub Pages

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout released version
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: './src'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
