# About: This action ensures that the Test-cartiva.ps1 scripts gets executed as a test on each commit
#
name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate project structure
        shell: pwsh
        run: ./scripts/Test-cartiva.ps1
